{% set name = "ancestry_hmm" %}
{% set version = "1.0" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/russcd/{{name}}/archive/refs/tags/v1.0.tar.gz
  sha256: 6b69a676af14fb5defb05fa1e852de0dc87cb49b8f22f97be2bd40933f24a475

build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - armadillo
  run:
    - armadillo

test:
  commands:
    - ancestry_hmm --help &> /dev/null

about:
  home: https://github.com/russcd/Ancestry_HMM
  license: GPL3
  license_file: LICENSE
  summary: "A Hidden Markov Model Approach for Simultaneously Estimating Local Ancestry and Admixture Time Using Next Generation Sequence Data in Samples of Arbitrary Ploidy"
  description: |
    Ancestry_HMM is a program designed to estimate local ancestry and admixture time using NGS data.

extra:
  identifiers:
    - https://doi.org/10.1371/journal.pgen.1006529 	# manuscript
